#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app.swagger_ui:
    path: /docapi
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
    path: /docapi/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }